### ISSUE TITLE
BUGs and TODOs

### ISSUE THREAD

**Issue by ScottCTD** [UofT-CS-Group/CSC110-Final-Project#50]
# Bugs

- [ ] https://github.com/UofT-CS-Group/CSC110-Final-Project/pull/49#issuecomment-991833430 
- [x] https://github.com/UofT-CS-Group/CSC110-Final-Project/pull/49#issuecomment-991834388
- [x] "None" marker disappear
- [x] https://github.com/UofT-CS-Group/CSC110-Final-Project/issues/50#issuecomment-991839309
- [x] https://github.com/UofT-CS-Group/CSC110-Final-Project/issues/50#issuecomment-991839829

# TODOs

- [x] https://github.com/UofT-CS-Group/CSC110-Final-Project/pull/49#pullrequestreview-829585303

Append to these lists if you got more bugs and features.

**Comment by Lei-Tin** [comment]
![image](https://user-images.githubusercontent.com/8016180/145701959-880d1be0-0b44-4874-95f1-f6d0d07e859a.png)
如果断网，删了一两个 Marker 直接启动，程序不会正常启动。

Terminal 直接报错
加个 Try Except 应该就可以正确引导到你那个 "Icons not initialized, some icons may not exist" 提示了

**Comment by Lei-Tin** [comment]
如果因为某种原因，你先打开了软件，Initialize 完了 Data
就算你连着网，再次点击 Initialize Data 后程序直接 Crash，提示读不到文件，建议再加个 Try Except
